### PR TITLE
prepare for the v2 release

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Comment by Stebalien** [comment]
Do we need a v2? This is the _first_ release at this path, so we should be able to go with v1, right?

**Comment by marten-seemann** [comment]
When you fork a repo, you also fork all its tags: https://github.com/libp2p/zeroconf/releases

**Comment by Stebalien** [comment]
Well... we can always delete those assuming we haven't pulled this through GOPROXY yet. And they'll all be broken.

**Comment by marten-seemann** [comment]
> Well... we can always delete those assuming we haven't pulled this through GOPROXY yet.

I wish... I deleted the tag *first, and then* ran
```bash
❯ go list -m -versions
github.com/libp2p/zeroconf v1.0.0
```
Apparently the proxy picked up the version, although I'm pretty sure nobody has ever imported our fork anywhere yet.

**Comment by Stebalien** [comment]
Looking at the go docs will also do that.

**Review by Stebalien — APPROVED** [review]

**Comment by marten-seemann** [comment]
> Looking at the go docs will also do that.

I'm guilty of doing that when I looked at what types / functions to un-export :(

**Pull request merged**
